version: "3"

services:
  user:
    image: node:14-alpine3.11
    working_dir: /app
    volumes:
      - ./user:/app
    ports:
      - 3000:3000
    # command: sh -c "npm i && npm run dev"
    stdin_open: true