version: "3"

services:
  user:
    image: node:14-alpine3.11
    working_dir: /app
    env_file: .env
    volumes:
      - ./user-api:/app
    ports:
      - 3000:3000
    command: sh -c "npm i && npm run dev"

  product:
    image: node:14-alpine3.11
    working_dir: /app
    env_file: .env
    volumes:
      - ./product-api:/app
    ports:
      - 3001:3000
    command: sh -c "npm i && npm run dev"

  payment:
    image: node:14-alpine3.11
    working_dir: /app
    env_file: .env
    volumes:
      - ./payment-api:/app
    ports:
      - 3002:3000
    command: sh -c "npm i && npm run dev"

  payment-creator:
    image: node:14-alpine3.11
    working_dir: /app
    env_file: .env
    volumes:
      - ./payment-creator:/app
    ports:
      - 3003:3000
    command: sh -c "npm i && npm run dev"

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: test
    ports:
      - 3017:27017

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
    ports:
      - 3432:5432

  redis:
    image: redis
    ports:
      - 3079:6379
